### PR TITLE
Array support

### PR DESCRIPTION
**Pull request by kjetilho**
This patch set fixes some bugs, and makes more aspects configurable.  Main feature is that you can have several local and remote networks, and sainfo for each combination will be created.
It should be backwards compatible, with one exception: association data has been moved into params for each remote to make the data structure in hiera-data easier to read.
Let me know if you want to break this into smaller pieces.

### CODE REVIEW

**Comment by inkblot** [comment]
There are several different development tasks all wrapped up in this PR. I'm going to try to take as much as I can in separate merges and see what's left to talk about.

**Comment by inkblot** [comment]
Ok, I've got the first few of your commits merged into master. Would you mind rebasing the remainder of the `array_support` branch onto master?

**Comment by kjetilho** [comment]
thanks.  yes, I was lazy in preparing the PR, thanks for picking anyway.

in general, just based on commit comments, are there any features you don't care for and I should omit in the next iteration?

**Comment by inkblot** [comment]
I'm not sure I understand the full scope of what's in this PR. I spent some time yesterday combing through the diffs. Apart from the commits I've already merged, is this a complete summary?

- Fine control over `racoon` and `setkey` restarts
- Subordination of associations to remotes
- Multiple-subnet tunnelling

Would it be possible to separate these from each other into distinct PRs?

Also, some notes on style in erb templates...

I would prefer all non-output code blocks to open on column 0 and suppress blank line output (`<%-` and `-%>` instead of `<%` and `%>`). Inside the non-output code blocks, the lowest level of Ruby is indented 4 spaces (to accommodate inlining the `<%-` token) and each higher indent level of Ruby code is indented with an additional 2 spaces. Basically, the `<%-` marker should never be indented, but the Ruby code inside the non-output block should use canonical Ruby indentation.

The templated text should use canonical indentation for the output file, independent of the indentation of the Ruby code. For `racoon.conf` and the setkey tunnel configuration files this is tab indentation. Ruby output blocks like `<%= params['lifetime'] %>` will be placed as needed in the templated text and should generally not contain complicated Ruby expressions.

**Comment by kjetilho** [comment]
we're abandoning racoon for strongswan, so I'm sorry I can spend time on updating the PR.
thank you for your module!

**Pull request closed without merging**
